name: Build pza-emu-tenma-72-2710

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Cmake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.22.1
        ninjaVersion: 1.11.1

    - name: Install arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      

    - name: Create build dir
      working-directory: pico-firmware
      run: >
        mkdir -p build

    - name: Build configuration
      working-directory: pico-firmware/build
      run: >
        cmake
        ..

    - name: Make!
      working-directory: pico-firmware/build
      run: >
        make
        

    - run: ls -la pico-firmware/build/src

    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pza-emu-tenma-72-2710
        path: pico-firmware/build/src/serial.uf2
